kind: pipeline
type: docker
name: build-jekyll-website

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Gemfile" }}_{{ checksum "Gemfile.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - 'vendor'
    volumes:
      - name: cache
        path: /tmp/cache
   
  - name: build-resource
    image: ruby:3.0
    commands:
      - gem install bundler jekyll
      - bundle install --path vendor/ruby
      - bundle exec jekyll build
  
  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Gemfile" }}_{{ checksum "Gemfile.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - 'vendor'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: deploy-south-cn
    image: node:15.13.0-alpine3.10
    commands:
      - env
      - date
      - echo TENCENT_SECRET_ID=$TENCENT_TEMP_SECRET_ID >> .env
      - echo TENCENT_SECRET_KEY=$TENCENT_TEMP_SECRET_KEY >> .env
      - echo TENCENT_TOKEN=$TENCENT_TEMP_TOKEN >> .env
      - echo TENCENT_APP_ID=$TENCENT_APP_ID >> .env
      - echo SERVERLESS_PLATFORM_VENDOR=tencent >> .env
      - echo SERVERLESS_PLATFORM_STAGE=$SERVERLESS_PLATFORM_STAGE >> .env
      - npm install -g serverless
      - sls -v
trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /ext-data/drone-cache