kind: pipeline
type: docker
name: build-jekyll-website

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Gemfile" }}_{{ checksum "Gemfile.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - 'vendor'
    volumes:
      - name: cache
        path: /tmp/cache
   
  - name: build-resource
    image: ruby:3.0
    commands:
      - gem install bundler jekyll
      - bundle config set --local path 'vendor/ruby'
      - bundle install
      - bundle exec jekyll build

  - name: deploy-south-cn
    image: node:15.13.0-alpine3.10
    environment:
      TENCENT_COS_SECRET_ID:
        from_secret: TENCENT_COS_SECRET_ID
      TENCENT_COS_SECRET_KEY:
        from_secret: TENCENT_COS_SECRET_KEY
      BUCKET_NAME:
        from_secret: BUCKET_NAME
      BUCKET_REGION:
        from_secret: BUCKET_REGION
    commands:
      - date
      - npm install
      - node cos.js

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Gemfile" }}_{{ checksum "Gemfile.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - 'vendor'
    volumes:
      - name: cache
        path: /tmp/cache

trigger:
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /ext-data/drone-cache