# Site settings
title: Oliver Blog
SEOTitle: Oliver Blog
header-img: img/bg.jpg
email: lizhizhi7@outlook.com
description: "Right here waiting for you."
keyword: "Oliver Blog, MATLAB, R, ML, Python, Machine Learning"
url: "https://blog.minizhi.cn"                                  # your host, for absolute URL
baseurl: ""                                                     # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lizhizhi7/lizhizhi7.github.io" # you code repository

# Sidebar settings
sidebar: true                                                   # whether or not using Sidebar.
sidebar-about-description: "Good Good Study , Day Day Up"
sidebar-avatar: /img/about_me.JPG                               # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     li-zhi-93-94
github_username:    lizhizhi7
facebook_username:  lee.minizhi
jianshu_username:   a5f544474e9c
#twitter_username:

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Featured Tags
featured-tags: true              # 是否使用首页标签
featured-condition-size: 2       # 相同标签数量大于这个数，才会出现在首页

# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    },{
        title: "Android",
        href: "https://www.android.com/"
    },{
        title: "Android Developer",
        href: "https://developer.android.com/"
    }
]

# Gitalk
gitalk:
  enable: true
  clientID: 7194056b4e3867bdf12c                            #Github clientID
  clientSecret: 0ee17ceedb52c45e6a8553399a0fbeaab0e9f43f    #Github clientSecret
  repo: lizhizhi7.github.io    #仓库名称
  owner: lizhizhi7    #repo拥有者
  admin: lizhizhi7    #repo管理员
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Gems from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown&Highlighter settings
# using kramdown and rouge for official support
# http://jekyllrb.com/docs/configuration/#kramdown
# https://github.blog/2016-02-01-github-pages-now-faster-and-simpler-with-jekyll-3-0/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM       # use Github Flavored Markdown !important

# Build setting
permalink: pretty # https://jekyllrb.com/docs/permalinks/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true    # if you want to customize anchor. check out line:181 of `post.html`

# Analytics
ba_track_id: b945c62a0417a859c3c7fbea0d9c29d3
ga_track_id: 'UA-142225576-1'